In [3]:
import numpy as np

FROM A PYTHON LIST

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

BUILT-IN METHODS

arange

In [10]:
np.arange(0,10)   #arange(start,end)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)   #arange(start,end,step)

array([0, 2, 4, 6, 8])

zeros and ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace

In [18]:
np.linspace(0,10,3)    #0-10 is divided into 3 parts

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,50)     #0-10 is divided into 50 parts

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

Creates an identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

RANDOM

Creates an array of random numbers

rand

Create an array of given shape and populate it with random samples from a uniform distribution over [0,1)

In [21]:
np.random.randint(1,50)

25

In [22]:
np.random.randint(1,50)

4

In [23]:
np.random.rand(2)   #generates 2 random values between 0 and 1

array([0.85886895, 0.1834217 ])

In [24]:
np.random.rand(5,5)      #generates 5 X 5 maatrix of numbers between 0 and 1

array([[0.11965469, 0.54574538, 0.45363369, 0.46705266, 0.09113268],
       [0.89892585, 0.96616544, 0.63840514, 0.0763477 , 0.25338904],
       [0.73711867, 0.05023591, 0.10793659, 0.10113004, 0.57436336],
       [0.44449573, 0.72945124, 0.33820371, 0.90085712, 0.32248938],
       [0.40044048, 0.57293957, 0.08476421, 0.47413958, 0.75272755]])

randn

Return a sample from the "Standard Normal" Distribution.

In [25]:
np.random.randn(2)

array([-1.74461448, -1.89136623])

In [26]:
np.random.randn(5,5)

array([[-0.25638787,  0.76705798, -0.018236  , -0.57327244, -0.19829224],
       [-1.11606987, -2.55986748,  0.12862724,  0.13718739,  0.27346925],
       [ 0.42507522, -0.11191507,  0.6605378 , -0.08051703, -0.66596482],
       [-1.51528276,  1.24864574,  1.69063837, -0.75197302, -1.11416033],
       [-0.30139026,  0.87535606, -0.28182669,  0.432857  ,  0.71227337]])

randint

Return random integers from low(inclusive) to high(exclusive)

In [27]:
np.random.randint(1,100)

91

In [28]:
np.random.randint(1,100,10)

array([65, 80, 57, 48, 37, 19, 97, 24, 68, 72])

ARRAY ATTRIBUTES AND METHODS

In [29]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
ranarr 

array([35, 35, 37, 17,  9, 41, 31, 46, 22, 35])

Reshape

In [32]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

max,min,argmax,agrmin

In [33]:
ranarr

array([35, 35, 37, 17,  9, 41, 31, 46, 22, 35])

In [35]:
ranarr.max()

46

In [36]:
ranarr.argmax()  #index of maximum value

7

In [37]:
ranarr.min()

9

In [38]:
ranarr.argmin()   #index of minimum value

4

Shape

In [39]:
arr.shape   #vector

(24,)

In [40]:
arr.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [41]:
arr.reshape(1,24).shape

(1, 24)

In [42]:
arr.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [43]:
arr.reshape(24,1).shape

(24, 1)

dtype

Gives data-type of the array

In [44]:
arr.dtype

dtype('int64')